channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - git
  - nodejs
  - jupyter-server-proxy
  - panel
  - pip:
    - git+https://github.com/LiberTEM/LiberTEM-panel-ui
    - rosettasciio
